import type { Teacher } from "@/lib/types"

export const mockTeachers: Teacher[] = [
  {
    id: "1",
    name: "Sarah Chen",
    title: "Mathematics & Physics Specialist",
    bio: "Expert in helping students master advanced calculus and quantum physics with interactive visualizations and real-world applications.",
    avatar: "/professional-teacher-woman.jpg",
    rating: 4.9,
    reviews: 156,
    hourlyRate: 45,
    subjects: ["Mathematics", "Physics", "Calculus"],
    experience: 12,
    languages: ["English", "Mandarin"],
    availability: "Weekdays & Weekends",
    responseTime: 2,
  },
  {
    id: "2",
    name: "James Williams",
    title: "English Literature & Writing Coach",
    bio: "Passionate about developing critical reading skills and helping students express themselves through compelling writing.",
    avatar: "/professional-teacher-man.jpg",
    rating: 4.8,
    reviews: 203,
    hourlyRate: 40,
    subjects: ["English", "Literature", "Writing"],
    experience: 15,
    languages: ["English"],
    availability: "Weekdays",
    responseTime: 1,
  },
  {
    id: "3",
    name: "Maria Rodriguez",
    title: "Spanish & History Tutor",
    bio: "Native Spanish speaker with expertise in European and Latin American history. Make learning engaging and fun.",
    avatar: "/professional-teacher-woman-spanish.jpg",
    rating: 4.7,
    reviews: 89,
    hourlyRate: 35,
    subjects: ["Spanish", "History", "Social Studies"],
    experience: 8,
    languages: ["Spanish", "English", "French"],
    availability: "Flexible",
    responseTime: 3,
  },
  {
    id: "4",
    name: "Alex Johnson",
    title: "Computer Science & Programming",
    bio: "Full-stack developer teaching Python, JavaScript, and web development to beginners through advanced students.",
    avatar: "/professional-teacher-programming.jpg",
    rating: 4.9,
    reviews: 124,
    hourlyRate: 55,
    subjects: ["Computer Science", "Python", "Web Development"],
    experience: 10,
    languages: ["English"],
    availability: "Evenings & Weekends",
    responseTime: 1,
  },
  {
    id: "5",
    name: "Emma Wilson",
    title: "Biology & Chemistry Expert",
    bio: "Making science tangible through hands-on explanations and lab-based learning approaches.",
    avatar: "/professional-teacher-science.jpg",
    rating: 4.8,
    reviews: 142,
    hourlyRate: 42,
    subjects: ["Biology", "Chemistry", "Science"],
    experience: 11,
    languages: ["English"],
    availability: "Weekdays & Weekends",
    responseTime: 2,
  },
  {
    id: "6",
    name: "David Patel",
    title: "SAT/ACT Test Prep Specialist",
    bio: "Helped over 500 students achieve their target scores with proven strategies and personalized study plans.",
    avatar: "/professional-teacher-test-prep.jpg",
    rating: 4.95,
    reviews: 287,
    hourlyRate: 60,
    subjects: ["SAT", "ACT", "Test Prep"],
    experience: 13,
    languages: ["English"],
    availability: "Flexible",
    responseTime: 1,
  },
]

export const mockUser = {
  id: "student-1",
  email: "student@example.com",
  name: "Alex Student",
  role: "student" as const,
  isAuthenticated: false,
}
